- hosts: all

  become: true
  gather_facts: False

  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Add Docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Google Cloud SDK Repo key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
        state: present

    - name: Add the Azure CLI signing key
      apt_key:
        keyserver: packages.microsoft.com
        id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: Set up the docker stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        tags:
          - docker

    - name: Set up the Google Cloud SDK repository
      apt_repository:
        repo: deb [arch=amd64] http://packages.cloud.google.com/apt xenial main
        state: present
          
    - name: Set up the Azure CLI repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ xenial main
        state: present
        update_cache: yes


    - name: Installing packages from apt
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - nginx
          - packer
          - lsb-release
          - apt-transport-https 
          - ca-certificates
          - dirmngr 
          - curl 
          - gnupg-agent 
          - software-properties-common
          - docker-ce
          - google-cloud-sdk
          - git
          - azure-cli
          - awscli

    - name: Execute install script
      become_user: root
      command: whoami
